extends: base.j2
language: fr
header_image: home-fr.png
default_block: post
sidebar:
    -
        name: PROGRAMME %PARTIEL%
        url: http://schedule2013.rmll.info/?lang=fr
    -
        name: RÉSERVATIONS
        url: https://reservation.rmll.info


