extends: base.j2
language: fr
header_image: header-home-fr.png
default_block: post
sidebar:
    -
        name: PROGRAMME %TEMPORAIRE%
        url: http://schedule2013.rmll.info
    -
        name: %RÉSERVATIONS%
        url: https://reservation.rmll.info


