extends: base.j2
language: fr
default_block: post
sidebar:
    -
        name: RMLL %2012%
        url: http://2012.rmll.info/
    -
        name: DOSSIER DE %CANDIDATURE% (PDF)
        url: /assets/candidature-bruxelles.pdf


