extends: base.j2
language: fr
header_image: header-home-fr.png
default_block: post
sidebar:
    -
        name: APPEL À %CONFÉRENCES%
        url: /fr/ac.html
    -
        name: PARTENAIRES ET %SPONSORS%
        url: /fr/partenaires-et-sponsors.html


