---
extends: base.j2
default_block: post
header_image: header-home-en.png
language: en
sidebar:
    -
        name: TEMPORARY %SCHEDULE%
        url: http://schedule2013.rmll.info
    -
        name: '%BOOKING%'
        url: https://reservation.rmll.info
