---
extends: base.j2
default_block: post
header_image: header-home-en.png
language: en
sidebar:
    -
        name: %CALL% FOR PAPERS
        url: /en/cfp.html
    -
        name: PARTNERS AND %SPONSORS%
        url: /en/partners-and-sponsors.html
