---
extends: base.j2
default_block: post
header_image: home-en.png
language: en
sidebar:
    -
        name: PARTIAL %PROGRAM%
        url: http://schedule2013.rmll.info/?lang=en
    -
        name: '%BOOKING%'
        url: https://reservation.rmll.info
