language: nl
header_image: home-nl.png
sidebar:
    -
        name: %PROGRAMMA%
        url: http://schedule2013.rmll.info/?lang=nl
    -
        name: '%BOOKING%'
        url: https://reservation.rmll.info
