language: nl
header_image: header-home-nl.png
sidebar:
    -
        name: TEMPORARY %SCHEDULE%
        url: http://schedule2013.rmll.info
    -
        name: '%BOOKING%'
        url: https://reservation.rmll.info
