language: nl
header_image: header-home-nl.png
sidebar:
    -
        name: CALL FOR %PAPERS%
        url: /nl/cfp.html
    -
        name: PARTNERS AND %SPONSORS%
        url: /en/partners-and-sponsors.html
